FROM node:22-alpine
WORKDIR /app
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_CHAIN_ID
ARG NEXT_PUBLIC_CHAIN_NAME
ARG NEXT_PUBLIC_NATIVE_SYMBOL
ARG NEXT_PUBLIC_RPC_URL
ARG NEXT_PUBLIC_BLOCK_EXPLORER_URL
ARG NEXT_PUBLIC_PUMP_FACTORY_ADDRESS
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID \
    NEXT_PUBLIC_CHAIN_NAME=$NEXT_PUBLIC_CHAIN_NAME \
    NEXT_PUBLIC_NATIVE_SYMBOL=$NEXT_PUBLIC_NATIVE_SYMBOL \
    NEXT_PUBLIC_RPC_URL=$NEXT_PUBLIC_RPC_URL \
    NEXT_PUBLIC_BLOCK_EXPLORER_URL=$NEXT_PUBLIC_BLOCK_EXPLORER_URL \
    NEXT_PUBLIC_PUMP_FACTORY_ADDRESS=$NEXT_PUBLIC_PUMP_FACTORY_ADDRESS
COPY package*.json turbo.json ./
COPY apps apps
COPY packages packages
RUN npm ci --ignore-scripts
RUN npm run build --workspace=@pumpnow/web
CMD ["npm", "run", "start", "--workspace=@pumpnow/web"]
